### ISSUE TITLE
Sort by title

### ISSUE THREAD

**Issue by YTSre** [kalvinmoraes/yts-angularjs#1]
When sorting by title (alphabetical) it gets the 

```
https://yts.io/api/v2/list_movies.json?order_by=desc&page=1&query_term=&sort_by=alphabetical
```

while it should be

```
https://yts.io/api/v2/list_movies.json?order_by=desc&page=1&query_term=&sort_by=title
```

Int he API call replace `alphabetical` with `title`

**Comment by anarqz** [comment]
Hey @YTSre ! It's good to hear from you!

Have just commited these changes. Thanks.

P.S.: in yts website the select option is set to "alphabetical" and not to "title" as you said for the API. Is there ok?

Thanks again for the support!
